---
title: "SALES_DATA_PIECHART"
author: "wyne maina"
date: "2026-03-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## LOAD THE NECESSARY PACKAGE
```{r}
library("ggplot2")
library("dplyr")
```
## GET THE WORKING DIRECTORY
```{r}
setwd("C:/Users/Admin/Desktop/DML")
```
##load the working directory
```{r}
library(readr)
df<- read_csv("student_performance (1).csv")
print(df)

```
## CREATE  A BAR CHART SHOWING NUMBER OF STUDENTS PER DEPARTMENT
```{r}
ggplot(df,aes(x=Department))+
  geom_bar(fill="pink")
labs(
  title = "The number of students per departments",
  x="Department",
  y="No. of student"
    )+theme_minimal()
```
## 1.CREATE a piechart showing the gender  distribution per department
```{r}
ggplot(df,aes(x=Department,fill=Gender))+
  geom_bar(position = "dodge")

```
# DRAW A BARGRAPH SHOWING GRADE DISTRIBUTION per gender
```{r}
library(ggplot2)

# Plot grade distribution per gender (Side-by-side)
ggplot(data, aes(x = gender, fill = grade)) +
  geom_bar(position = "dodge") +
  labs(title = "Grade Distribution by Gender",
       x = "Gender",
       y = "Count") +
  theme_minimal()


```
## SHOW GRADE DISTRIBUTION 
```{r}

ggplot(df, aes(x=Grade)) +
  geom_bar(fill="blue") +
  theme_minimal() +
  labs(title="Grade Distribution", x="Grade Category", y="Number of Students")
```
#GRADE DISTRIBUTION PER DEPARTMENT PER GENDER
```{r}
ggplot(df, aes(x = Department, fill = Gender)) +
  geom_bar(position = "dodge") +
  labs(
    title = "Grade Distribution by Gender",
    x = "Department",
    y = "Count"
  ) +
  theme_minimal()
```
```{r}
ggplot(df,aes(x=Gender,fill = Grade))+
  facet_wrap(~Department)+
  geom_bar(position = "dodge")



```